spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XIN
    username: XIN
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    password:
    timeout: 30000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
mybatis:
  mapper-locations: classpath:orclMapper/*Mapper.xml
  type-aliases-package: com.huanyue.spaceuserclient.entity

logging:
  level:
    com:
      huanyue:
        spaceuserclient:
          dao: debug
